server:
  port: 2003

#spring:
#  application:
#    name: seata-account-service
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver    #mysql驱动包
#    url: jdbc:mysql://localhost:3306/seata_account
#    username: root
#    password: 123456
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        namespace: b85f33a6-1a1f-4fa6-9a6b-dbef597e6f30
#        cluster-name: default
#      config:
#        server-addr: ${spring.cloud.nacos.discovery.server-addr}
#        namespace: b85f33a6-1a1f-4fa6-9a6b-dbef597e6f30
# ！！！！！！！！！！！！以下参数只能配置在bootstrap.yml文件中，配置在application.yml文件中的话读取不到！！！！！！！！
#        extension-configs:
#          - dataId: shared-seata.yaml
#            group: DEFAULT_GROUP
#            refresh: true
# ！！！！！！！！！！！！如果要配置在application.yml文件中，则必须是写seta本身的配置！！！！！！！！
# ！！！！！！！！！！！！application中不能以extension-configs读取到外部文件的配置！！！！！！！！
#seata:
#  enabled: true
#  tx-service-group: my_test_tx_group
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: 127.0.0.1:8848
#      group: SEATA_GROUP
#      namespace: b85f33a6-1a1f-4fa6-9a6b-dbef597e6f30
#      cluster: default
#  config:
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#      group: SEATA_GROUP
#      namespace: b85f33a6-1a1f-4fa6-9a6b-dbef597e6f30
#  service:
#    vgroupMapping:
#      my_test_tx_group: default

#feign:
#  hystrix:
#    enabled: false
#
#logging:
#  level:
#    io:
#      seata: info
#
#mybatis:
#  mapper-locations: classpath:mapper/*.xml