server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: b85f33a6-1a1f-4fa6-9a6b-dbef597e6f30
        cluster-name: default
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: b85f33a6-1a1f-4fa6-9a6b-dbef597e6f30
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver    #mysql驱动包
    url: jdbc:mysql://localhost:3306/seata_order
    username: root
    password: 123456
feign:
  hystrix:
    enabled: false
logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:/mapper/*.xml

seata:
  enabled: true
  tx-service-group: my_test_tx_group
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: b85f33a6-1a1f-4fa6-9a6b-dbef597e6f30
      cluster: default
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: b85f33a6-1a1f-4fa6-9a6b-dbef597e6f30
service:
  vgroupMapping:
    my_test_tx_group: default
